# Generated by Django 4.2 on 2025-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=100)),
                ("quantidade", models.IntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
